# Generated by Django 3.2.7 on 2021-09-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consumer',
            old_name='Address',
            new_name='address',
        ),
    ]
