# Generated by Django 3.2.7 on 2021-09-30 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_rename_address_consumer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumer',
            name='username',
        ),
        migrations.AddField(
            model_name='consumer',
            name='user',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
